/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.management;

import userInterface.carPool.*;
import business.carpool.CarInfo;
import business.dataoperations.DataStore;
import business.enterprise.Enterprise;
import business.enterprise.EnterpriseDirectory;
import business.management.CarListingRequest;
import business.management.ManagementCarRequestQueue;
import business.network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.io.InputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userInterface.sysadmin.SystemAdminWorkAreaJPanel;
import utils.EmailClient;

/**
 *
 * @author newzysharma
 * 
 */

public class CarDetails extends javax.swing.JPanel {
CarInfo info;
private JPanel panelRight;
private DataStore datastore;
private CarListingRequest carreq;
List<CarListingRequest> allRequests;
final static Logger logger = Logger.getLogger(CarDetails.class.getName());
Network n;
    /**
     * Creates new form BookCarViewDetails
     */
    public CarDetails(JPanel panelRight,CarListingRequest c,Enterprise e, List<CarListingRequest> r,Network n) {
        initComponents();
          this.panelRight=panelRight;
          this.datastore =e.getDatastore();
          this.carreq=c;
          displayCarDetails(carreq);
          this.allRequests=r;
          this.n=n;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void displayCarDetails(CarListingRequest car){
        
        CarInfo c = car.getCarinfo();
      jtxtcname.setText(c.getCarName());
      jtxtcmodel.setText(c.getCarModel());
        jtxtccolor.setText(c.getCarColor());
        jtxtctype.setText(c.getCarType());
        jtxtfdate.setText(String.valueOf(c.getFromDate()));
        jtxttdate.setText(String.valueOf(c.getToDate()));
        jtxtftime.setText(String.valueOf(c.getFromTime()));
        jtxtttime.setText(String.valueOf(c.getToTime()));
        jtxtstartpt.setText(c.getStartPoint());
        jtxtdropoffpt.setText(c.getDropOffPoint());
        jtxtaccupancy.setText(String.valueOf(c.getOccupancy()));
        jtxtflexdistance.setText(String.valueOf(c.getPickupTillFlexDist()));
        jtxtpostingUser.setText(c.getPostingUserName());
        //Download link to be provided here
       
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtfdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxttdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtftime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtttime = new javax.swing.JTextField();
        jtxtcname = new javax.swing.JTextField();
        jtxtccolor = new javax.swing.JTextField();
        jtxtctype = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtstartpt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtdropoffpt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtaccupancy = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtflexdistance = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jbtnBook = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtxtcmodel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtxtpostingUser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Name");

        jLabel2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Car Color");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Car Type");

        jLabel4.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From Date");

        jtxtfdate.setEditable(false);
        jtxtfdate.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To Date");

        jtxttdate.setEditable(false);
        jtxttdate.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxttdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("From Time");

        jtxtftime.setEditable(false);
        jtxtftime.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("To Time");

        jtxtttime.setEditable(false);
        jtxtttime.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtttimeActionPerformed(evt);
            }
        });

        jtxtcname.setEditable(false);
        jtxtcname.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcnameActionPerformed(evt);
            }
        });

        jtxtccolor.setEditable(false);
        jtxtccolor.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtccolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtccolorActionPerformed(evt);
            }
        });

        jtxtctype.setEditable(false);
        jtxtctype.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONFIRM BOOKING");

        jLabel9.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Starting Point");

        jtxtstartpt.setEditable(false);
        jtxtstartpt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtstartpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtstartptActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Drop Off Point");

        jtxtdropoffpt.setEditable(false);
        jtxtdropoffpt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Occupancy");

        jtxtaccupancy.setEditable(false);
        jtxtaccupancy.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtaccupancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaccupancyActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pick up Distance");

        jtxtflexdistance.setEditable(false);
        jtxtflexdistance.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtflexdistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtflexdistanceActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Posting User ID");

        jbtnBook.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBook.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnBook.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick.png"))); // NOI18N
        jbtnBook.setText("Approve");
        jbtnBook.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbtnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBookActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Car Model");

        jtxtcmodel.setEditable(false);
        jtxtcmodel.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DOWNLOAD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Proof Documents:");

        jtxtpostingUser.setEditable(false);
        jtxtpostingUser.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtpostingUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpostingUserActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mile(s)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtccolor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtctype, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtfdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtpostingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtaccupancy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jtxtflexdistance, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtstartpt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtftime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addComponent(jtxtcname, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtdropoffpt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxttdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtcmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtttime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(658, 658, 658)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtnBook))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(703, 703, 703)
                        .addComponent(jLabel8)))
                .addContainerGap(921, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel8)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtccolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jtxttdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtftime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jtxtttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtxtstartpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jtxtdropoffpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtxtaccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtxtflexdistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jtxtcmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(358, 358, 358)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtpostingUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBook)
                    .addComponent(jButton2))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxttdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttdateActionPerformed

    private void jtxtttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtttimeActionPerformed

    private void jtxtcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcnameActionPerformed

    private void jtxtccolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtccolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtccolorActionPerformed

    private void jtxtstartptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtstartptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtstartptActionPerformed

    private void jtxtaccupancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaccupancyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaccupancyActionPerformed

    private void jtxtflexdistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtflexdistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtflexdistanceActionPerformed

    private void jbtnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBookActionPerformed
    EnterpriseDirectory entDir = n.getEnterpriseDirectory();
    for(Enterprise e:entDir.getEnterpriseList()){
           if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.CarPool)){
               //added req to that users repo
                e.getDatastore().getCardir().getCarList().add(carreq.getCarinfo());
           }
       }
    for(CarListingRequest r: allRequests){
        if(r.getRequestNumber()==carreq.getRequestNumber()){
            allRequests.remove(r);
            break;
        }
    }
     JOptionPane.showMessageDialog(null, "Approved!","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
     jbtnBook.setEnabled(false);
      panelRight.remove(this);
        Component[] componentArray = panelRight.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRequestCarWorkArea manageReq = (ManageRequestCarWorkArea) component;
        manageReq.populateTable();
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
        EmailClient.sendEmail(carreq.getCarinfo().getPostingUserName(),"Car lising Approved!", "Dear user, Your car listing is approved by admin!");
      logger.info("Car listing approved "+carreq.getRequestNumber());
       panelRight.remove(this);
        Component[] componentArray1 = panelRight.getComponents();
        Component component1 = componentArray1[componentArray1.length - 1];
        ManageRequestCarWorkArea manageReq1 = (ManageRequestCarWorkArea) component1;
        manageReq1.populateTable();
        CardLayout layout1 = (CardLayout) panelRight.getLayout();
        layout1.previous(panelRight);
    }//GEN-LAST:event_jbtnBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
        File userDoc=new File(carreq.getDocumentPath()); 
        String[] filename = carreq.getDocumentPath().split("\\.");
        String fext = filename[filename.length-1];
        URL myUrl = userDoc.toURI().toURL();
        String[] name = carreq.getCarinfo().getPostingUserName().split("@");
        if(name[0]==""){
        name[0]=carreq.getCarinfo().getPostingUserName();
        } 
        File f = new File("./UserDocuments/"+name[0]+"_carPoolProof."+fext);
       // org.apache.commons.io.FileUtils.copyURLToFile(myUrl, f);
        JOptionPane.showMessageDialog(null, "File downloaded under /UserDocuments/"+name[0]+"_carPoolProof."+fext,"SUCCESS",JOptionPane.INFORMATION_MESSAGE);
       
        } catch(Exception e){
            //logger
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtpostingUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpostingUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpostingUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panelRight.remove(this);
        Component[] componentArray = panelRight.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRequestCarWorkArea manageReq = (ManageRequestCarWorkArea) component;
        manageReq.populateTable();
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBook;
    private javax.swing.JTextField jtxtaccupancy;
    private javax.swing.JTextField jtxtccolor;
    private javax.swing.JTextField jtxtcmodel;
    private javax.swing.JTextField jtxtcname;
    private javax.swing.JTextField jtxtctype;
    private javax.swing.JTextField jtxtdropoffpt;
    private javax.swing.JTextField jtxtfdate;
    private javax.swing.JTextField jtxtflexdistance;
    private javax.swing.JTextField jtxtftime;
    private javax.swing.JTextField jtxtpostingUser;
    private javax.swing.JTextField jtxtstartpt;
    private javax.swing.JTextField jtxttdate;
    private javax.swing.JTextField jtxtttime;
    // End of variables declaration//GEN-END:variables
}
