/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.management;

import business.enterprise.Enterprise;
import business.enterprise.EnterpriseDirectory;
import business.management.CarListingRequest;
import business.management.ManagementCarRequestQueue;
import business.network.Network;
import business.qnaPortal.Question;
import business.qnaPortal.QuestionDirectory;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.QnAPortal.ViewQuestionJPanel;

/**
 *
 * @author newzysharma
 */
public class ManageRequestCarWorkArea extends javax.swing.JPanel {
private JPanel userProcessContainer;
Enterprise enterprise;
Network network;
List<CarListingRequest> allRequests;
    /**
     * Creates new form ManageRequestWorkArea
     */
    public ManageRequestCarWorkArea(JPanel panelRight,Enterprise enterprise,Network n) {
        initComponents();
        this.userProcessContainer=panelRight;
        this.enterprise=enterprise;
        this.network=n;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        jbtnApprove = new javax.swing.JButton();
        jbtnApprove1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE CAR POOL REQUESTS");

        carTable.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Requested By", "Status", "Document type"
            }
        ));
        jScrollPane1.setViewportView(carTable);

        jbtnApprove.setBackground(new java.awt.Color(0, 0, 0));
        jbtnApprove.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnApprove.setForeground(new java.awt.Color(255, 255, 255));
        jbtnApprove.setText("VIEW DETAILS");
        jbtnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApproveActionPerformed(evt);
            }
        });

        jbtnApprove1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnApprove1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnApprove1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnApprove1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jbtnApprove1.setText("BACK");
        jbtnApprove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApprove1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(665, 665, 665)
                        .addComponent(jbtnApprove1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jbtnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(648, 648, 648)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnApprove)
                    .addComponent(jbtnApprove1))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApproveActionPerformed
         int selected = carTable.getSelectedRow();
        if(selected>=0){
         CarListingRequest carreq= (CarListingRequest)carTable.getValueAt(selected, 2);
        userProcessContainer.add("viewCarDetails", new CarDetails(userProcessContainer,carreq,enterprise,allRequests,network));
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row to display","Error",JOptionPane.ERROR_MESSAGE);
        }                        
      
    }//GEN-LAST:event_jbtnApproveActionPerformed

    private void jbtnApprove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApprove1ActionPerformed
 userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jbtnApprove1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnApprove;
    private javax.swing.JButton jbtnApprove1;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
       EnterpriseDirectory entDir = network.getEnterpriseDirectory();
       
       for(Enterprise e:entDir.getEnterpriseList()){
           if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.CarPool)){
                ManagementCarRequestQueue requests = e.getDatastore().getCarmngmntrqstqueue();
                 DefaultTableModel m = (DefaultTableModel)carTable.getModel();
                 m.setRowCount(0);
                 allRequests = requests.getRequests();
                 for(CarListingRequest r:requests.getRequests()){
                    m.addRow(new Object[]{r.getRequestNumber(),r.getCarinfo().getPostingUserName(),r,r.getDocumentType()});
                  }
           }
       }
    }
}
