/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.QnAPortal;

import business.enterprise.Enterprise;
import business.network.Network;
import business.qnaPortal.Answer;
import business.qnaPortal.AnswerDirectory;
import business.qnaPortal.Question;
import business.qnaPortal.QuestionDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import neuplexus.NEUPlexus;
import org.apache.log4j.Logger;
import userInterface.authentication.UserLogin;
import userInterface.homeSceen.NeuPlexusHome;
import userInterface.management.ManageRequestCarWorkArea;
import utils.EmailClient;
 /*
 * @author Shardul Pathak
 */
public class ViewQuestionJPanel extends javax.swing.JPanel {
    private JPanel panelRight;
    private Question q;
    final static Logger logger = Logger.getLogger(ViewQuestionJPanel.class.getName());

    /**
     * Creates new form ViewQuestionJPanel
     */
    public ViewQuestionJPanel(JPanel panelRight,Question q) {
        initComponents();
         this.panelRight=panelRight;
         this.q=q;
         if(NeuPlexusHome.useraccount.getRole().toString().equalsIgnoreCase("AdminRole")){
             btnReply.setVisible(false);
             yourAnswerLabel.setVisible(false);
             answerTxt.setVisible(false);
             jScrollPane2.setVisible(false);
         }
         populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReply = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        yourAnswerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        answerTxt = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        askedByTxt = new javax.swing.JLabel();
        datePostedTxt = new javax.swing.JLabel();
        qstnLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        bigPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        btnReply.setBackground(new java.awt.Color(0, 0, 0));
        btnReply.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        btnReply.setForeground(new java.awt.Color(255, 255, 255));
        btnReply.setText("REPLY");
        btnReply.setToolTipText("");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VIEW QUESTION");

        yourAnswerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        yourAnswerLabel.setText("Your Answer:");

        answerTxt.setColumns(20);
        answerTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        answerTxt.setRows(5);
        jScrollPane2.setViewportView(answerTxt);

        jLabel3.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Asked By:");

        jLabel4.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Posted:");

        askedByTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        askedByTxt.setForeground(new java.awt.Color(255, 255, 255));
        askedByTxt.setText("jLabel2");

        datePostedTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        datePostedTxt.setForeground(new java.awt.Color(255, 255, 255));
        datePostedTxt.setText("jLabel2");

        qstnLabel.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        qstnLabel.setForeground(new java.awt.Color(255, 255, 255));
        qstnLabel.setText("Label Q");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        bigPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bigPanelLayout = new javax.swing.GroupLayout(bigPanel);
        bigPanel.setLayout(bigPanelLayout);
        bigPanelLayout.setHorizontalGroup(
            bigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        bigPanelLayout.setVerticalGroup(
            bigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(bigPanel);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Answers:");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Question:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(qstnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(askedByTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(datePostedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(yourAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane2))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(696, 696, 696)
                        .addComponent(jButton1)
                        .addGap(89, 89, 89)
                        .addComponent(btnReply))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(783, 783, 783)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(askedByTxt))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(datePostedTxt)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(qstnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19))))
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yourAnswerLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnReply, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Component[] componentArray1 = panelRight.getComponents();
        Component component1 = componentArray1[componentArray1.length - 1];
        ViewQuestions manageReq1 = (ViewQuestions) component1;
        manageReq1.printQuestionsTable();
        CardLayout layout1 = (CardLayout) panelRight.getLayout();
        layout1.previous(panelRight);
       // panelRight.remove(this);
        //CardLayout layout = (CardLayout) panelRight.getLayout();
        //layout.previous(panelRight);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
        String Answer = answerTxt.getText();
        String userName = NeuPlexusHome.useraccount.getLastName() + ", " + NeuPlexusHome.useraccount.getFirstName();
        Answer answer = new Answer(Answer, userName, q.getQuestionId());
        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm");
        answer.setAnsweredTime(dateFormat.format(date));

        //post reply to each network
      /*  NEUPlexus system = UserLogin.system;
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.QnAPortal)) {
                    if (e.getDatastore().getQuesdir().getQuestionList().contains(q)) {*/
                        q.getAnswers().getAnswerList().add(answer);
                    /*}
                }
            }
        }*/
        answerTxt.setText("");
        populateTable();
        if (!q.getAskedByEmailId().equalsIgnoreCase(NeuPlexusHome.useraccount.getUserName())) {
            EmailClient.sendEmail(q.getAskedByEmailId(),
                    "User" + " " + NeuPlexusHome.useraccount.getUserName() + ",has posted a reply on your question.",
                    "User" + " " + NeuPlexusHome.useraccount.getUserName() + " " + "has replied:\n" + answerTxt.getText());
        }
    }//GEN-LAST:event_btnReplyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerTxt;
    private javax.swing.JLabel askedByTxt;
    private javax.swing.JPanel bigPanel;
    private javax.swing.JButton btnReply;
    private javax.swing.JLabel datePostedTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel qstnLabel;
    private javax.swing.JLabel yourAnswerLabel;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        try{
        qstnLabel.setText(q.getQuestionText());
        askedByTxt.setText(q.getAskedBy());
        datePostedTxt.setText(q.getDatePosted());
        
      bigPanel.removeAll();
      bigPanel.revalidate();
      bigPanel.repaint();
      bigPanel.setLayout(new BoxLayout(bigPanel,BoxLayout.Y_AXIS));
        for(Answer a:q.getAnswers().getAnswerList()){
            JLabel l = new JLabel();
            String value = "<html><br></br>" + a.getAnswerText() + "<br>Answered by: " +a.getAnsweredByUserId() + "  on " +a.getAnsweredTime()+"<br></br>";
            l.setText(value);
            Font font = l.getFont();
            // same font but bold
            Font boldFont = new Font(font.getFontName(), Font.BOLD, 14);
            l.setForeground(Color.white);
            l.setFont(boldFont);
            bigPanel.add(l);
       }
         bigPanel.revalidate();
         bigPanel.repaint();
        }catch(Exception e){
            logger.error("Exception while printing question answer table "+e.getStackTrace());
        }
       }
    
}
