/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.QnAPortal;

import business.dataoperations.DataStore;
import business.qnaPortal.Question;
import business.qnaPortal.QuestionDirectory;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userInterface.carPool.BookCarViewDetails;
import userInterface.homeSceen.NeuPlexusHome;

/**
 *
 * @author Shardul Pathak
 */
public class ViewQuestions extends javax.swing.JPanel {
private JPanel panelRight;
private DataStore datastore;
final static Logger logger = Logger.getLogger(ViewQuestions.class.getName());
    /**
     * Creates new form ViewQuestions
     */
    public ViewQuestions(JPanel panelRight,DataStore datastore) {
        initComponents();
        this.panelRight=panelRight;
        this.datastore=datastore;
        printQuestionsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionsTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUESTIONS");

        questionsTable.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        questionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question ID", "Category", "Question", "Answered by"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        questionsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                questionsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(questionsTable);

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewBtn.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("VIEW");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(625, 625, 625)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        try{
        int selected = questionsTable.getSelectedRow();
        if(selected>=0){
         Question q= (Question)questionsTable.getValueAt(selected, 0);
        panelRight.add("viewQuestion", new ViewQuestionJPanel(panelRight,q));
        CardLayout layout = (CardLayout)panelRight.getLayout();
           layout.next(panelRight);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row to display","Error",JOptionPane.ERROR_MESSAGE);
        }                        
        }catch(Exception e){
            logger.error("Exception in view question "+e.getStackTrace());
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        panelRight.remove(this);
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
    }//GEN-LAST:event_backBtnActionPerformed

    private void questionsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_questionsTableMouseClicked
       int selected = questionsTable.getSelectedRow();
        if(selected>=0){
            Question q= (Question)questionsTable.getValueAt(selected, 0);
            if(q.getAskedByEmailId().equalsIgnoreCase(NeuPlexusHome.useraccount.getUserName())){
                btnDelete.setEnabled(true);
            }else{
                btnDelete.setEnabled(false);
            }
        }
    }//GEN-LAST:event_questionsTableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
        int selected = questionsTable.getSelectedRow();
        if(selected>=0){
            Question q= (Question)questionsTable.getValueAt(selected, 0);
            QuestionDirectory qdir = datastore.getQuesdir();
            qdir.getQuestionList().remove(q);
            JOptionPane.showMessageDialog(null, "Question deleted successfully!","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
            printQuestionsTable();
        }
        }catch(Exception e){
            logger.error("Exception while deleting question "+e.getStackTrace());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    public void printQuestionsTable() {
        try{
        btnDelete.setEnabled(false);
        QuestionDirectory qdir = datastore.getQuesdir();
        DefaultTableModel m = (DefaultTableModel)questionsTable.getModel();
        m.setRowCount(0);
        for(Question q:qdir.getQuestionList()){
           m.addRow(new Object[]{q,q.getQuestionType(),q.getQuestionText(),q.getNumberOfAnswers()});
        }
        }catch(Exception e){
            logger.error("Exception while printing question table "+e.getStackTrace());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable questionsTable;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
