

package userInterface.adminuser;

import business.enterprise.Enterprise;
import business.role.Role;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.homeSceen.NeuPlexusHome;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        showanalysisbtn();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnManageAdmin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnViewAnalysis = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 120, 30));

        valueLabel.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 190, 30));

        btnManageAdmin.setBackground(new java.awt.Color(153, 0, 0));
        btnManageAdmin.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        btnManageAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnManageAdmin.setText("Manage Organization");
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        add(btnManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Manage Users");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 200, 30));

        btnViewAnalysis.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnViewAnalysis.setText("View Analysis");
        btnViewAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAnalysisActionPerformed(evt);
            }
        });
        add(btnViewAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
       ManageOrganizationJPanel selectent = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("selectEnterpriseJPanel", selectent);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ManageUsersAdminJPanel selectent = new ManageUsersAdminJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("selectEnterpriseJPanel", selectent);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAnalysisActionPerformed
        // TODO add your handling code here:
                 AnalysisChart analysisChart = new AnalysisChart(userProcessContainer, enterprise);

        userProcessContainer.add("analysisChart",analysisChart);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewAnalysisActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnViewAnalysis;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    private void showanalysisbtn() {
      if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Management)){
          btnViewAnalysis.setVisible(false);
      }
      else
          btnViewAnalysis.setVisible(true);
    }
    
}
