/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.adminuser;

import userInterface.accomodation.*;
import business.accomodation.Accomodation;
import business.accomodation.AccomodationDirectory;
import business.carpool.BookingDetails;
import business.carpool.CarDirectory;
import business.carpool.CarInfo;
import business.dataoperations.DataStore;
import business.management.AccomodationListRequest;
import business.userAccount.User;
import business.userAccount.UserDirectory;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userInterface.homeSceen.NeuPlexusHome;
import utils.EmailClient;

/**
 *
 * @author newzysharma
 */
public class ViewUsers extends javax.swing.JPanel {
    
    private JPanel panelRight;
    private UserDirectory uDir;
    final static Logger logger = Logger.getLogger(ViewUsers.class.getName());
    /**
     * Creates new form ViewBookingsWorkArea
     */
    public ViewUsers(JPanel panelRight, UserDirectory uDir) {
        initComponents();
        this.panelRight = panelRight;
        this.uDir = uDir;
        printUserListTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewUserTable = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW USERS");

        viewUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUID", "Username", "Full name", "Campus", "Contact number", "Role"
            }
        ));
        jScrollPane1.setViewportView(viewUserTable);

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBack.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(787, 787, 787)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(697, 697, 697)
                        .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnDelete)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBack)
                    .addComponent(btnDelete))
                .addContainerGap(495, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selected = viewUserTable.getSelectedRow();
        if (selected >= 0) {
            User u = (User) viewUserTable.getValueAt(selected, 1);
            for (User user : uDir.getUserDir()) {
                if (user.toString().equalsIgnoreCase(u.getUserName())) {
                    if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        uDir.getUserDir().remove(user);
                        JOptionPane.showMessageDialog(null, "User deleted successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        logger.info("User deleted "+user.getUserName());
                        printUserListTable();
                        break;
                    } else {
                        return;
                    }

                }
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
 panelRight.remove(this);
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
    }//GEN-LAST:event_jbtnBackActionPerformed
 
     private void printUserListTable() {
         try{
             viewUserTable.setAutoscrolls(true);
        DefaultTableModel m = (DefaultTableModel) viewUserTable.getModel();
          m.setRowCount(0);
        for(User u:uDir.getUserDir()){
            if(u.getNUID()!=0 && u.getFirstName()!=null && u.getLastName()!=null && u.getMiddleName()!=null && u.getCampusName()!=null && u.getContactNumber()!=null)
                m.addRow(new Object[]{u.getNUID(),u,u.getFirstName()+" "+u.getMiddleName()+" "+u.getLastName(),u.getCampusName(),u.getContactNumber(),u.getRole().toString()});
            }
    
     }catch(Exception e){
    logger.error("Exception while populating users "+e.getStackTrace());
     }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JTable viewUserTable;
    // End of variables declaration//GEN-END:variables
}
