/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.carPool;

import business.carpool.BookingDetails;
import business.carpool.CarDirectory;
import business.carpool.CarInfo;
import business.dataoperations.DataStore;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import userInterface.authentication.UserLogin;
import userInterface.homeSceen.NeuPlexusHome;
import userInterface.sysadmin.ManageNetworkJPanel;
import utils.EmailClient;

/**
 *
 * @author newzysharma
 * 
 */

public class BookCarViewDetails extends javax.swing.JPanel {
CarInfo info;
private JPanel panelRight;
private DataStore datastore;
private CarInfo c;
final static Logger logger = Logger.getLogger(BookCarViewDetails.class.getName());
    /**
     * Creates new form BookCarViewDetails
     */
    public BookCarViewDetails(JPanel panelRight,CarInfo c,DataStore datastore) {
        initComponents();
          this.panelRight=panelRight;
          this.datastore =datastore;
          this.c=c;
          displayCarDetails(c);
          hideBooking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void displayCarDetails(CarInfo c){
        
      jtxtcname.setText(c.getCarName());
      jtxtcmodel.setText(c.getCarModel());
        jtxtccolor.setText(c.getCarColor());
        jtxtctype.setText(c.getCarType());
        jtxtfdate.setText(String.valueOf(c.getFromDate()));
        jtxttdate.setText(String.valueOf(c.getToDate()));
        jtxtftime.setText(String.valueOf(c.getFromTime()));
        jtxtttime.setText(String.valueOf(c.getToTime()));
        jtxtstartpt.setText(c.getStartPoint());
        jtxtdropoffpt.setText(c.getDropOffPoint());
        jtxtaccupancy.setText(String.valueOf(c.getOccupancy()));
        jtxtflexdistance.setText(String.valueOf(c.getPickupTillFlexDist()));
        postingTxt.setText(c.getPostingUserName());
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtfdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxttdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtftime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtttime = new javax.swing.JTextField();
        jtxtcname = new javax.swing.JTextField();
        jtxtccolor = new javax.swing.JTextField();
        jtxtctype = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtstartpt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtdropoffpt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtaccupancy = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtflexdistance = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jbtnBook = new javax.swing.JButton();
        jtxtcmodel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        postingTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Name");

        jLabel2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Car Color");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Car Type");

        jLabel4.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From Date");

        jtxtfdate.setEditable(false);
        jtxtfdate.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To Date");

        jtxttdate.setEditable(false);
        jtxttdate.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxttdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("From Time");

        jtxtftime.setEditable(false);
        jtxtftime.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("To Time");

        jtxtttime.setEditable(false);
        jtxtttime.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtttimeActionPerformed(evt);
            }
        });

        jtxtcname.setEditable(false);
        jtxtcname.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcnameActionPerformed(evt);
            }
        });

        jtxtccolor.setEditable(false);
        jtxtccolor.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtccolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtccolorActionPerformed(evt);
            }
        });

        jtxtctype.setEditable(false);
        jtxtctype.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONFIRM BOOKING");

        jLabel9.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Starting Point");

        jtxtstartpt.setEditable(false);
        jtxtstartpt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtstartpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtstartptActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Drop Off Point");

        jtxtdropoffpt.setEditable(false);
        jtxtdropoffpt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Occupancy");

        jtxtaccupancy.setEditable(false);
        jtxtaccupancy.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtaccupancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaccupancyActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pick up Distance");

        jtxtflexdistance.setEditable(false);
        jtxtflexdistance.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jtxtflexdistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtflexdistanceActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Posting User ID");

        jbtnBook.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBook.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnBook.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick.png"))); // NOI18N
        jbtnBook.setText("BOOK");
        jbtnBook.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbtnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBookActionPerformed(evt);
            }
        });

        jtxtcmodel.setEditable(false);
        jtxtcmodel.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        postingTxt.setEditable(false);
        postingTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Car Model");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxtfdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jtxtftime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jtxtstartpt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jtxtcname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jtxtflexdistance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jtxtaccupancy, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jtxtctype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtxtccolor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel14))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtcmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxttdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtttime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtdropoffpt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(postingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(742, 742, 742)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(720, 720, 720)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jbtnBook)))
                .addContainerGap(1007, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel8)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtcmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtccolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxttdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtftime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jtxtttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtstartpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jtxtdropoffpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtaccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtflexdistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBook)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxttdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttdateActionPerformed

    private void jtxtttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtttimeActionPerformed

    private void jtxtcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcnameActionPerformed

    private void jtxtccolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtccolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtccolorActionPerformed

    private void jtxtstartptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtstartptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtstartptActionPerformed

    private void jtxtaccupancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaccupancyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaccupancyActionPerformed

    private void jtxtflexdistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtflexdistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtflexdistanceActionPerformed

    private void jbtnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBookActionPerformed
try{
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
	String date = dateFormat.format(new Date());
        dateFormat =  new SimpleDateFormat("HH:mm"); 
        String time = dateFormat.format(new Date());
        BookingDetails detail = new BookingDetails(NeuPlexusHome.useraccount.getUserName(), date, time);
        detail.setBookingId();
        for(BookingDetails b:c.getBookingUserNames()){
            if(b.getUserID().equals(detail.getUserID())){
                JOptionPane.showMessageDialog(null, "You have already booked this car!","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        c.getBookingUserNames().add(detail);
        int occ=c.getOccupancy();
        occ = occ-1;
        c.setOccupancy(occ);
        if(occ==0){
            CarDirectory carDir = datastore.getCardir();
            for(CarInfo car:carDir.getCarList()){
                if(car.equals(c)){
                    car.setBooked(true);
                    break;
                }
            }
        }
        BookingConfirmation bookingConf=new BookingConfirmation(panelRight);
        EmailClient.sendEmail(NeuPlexusHome.useraccount.getUserName(), "Car booked successfully!", "Dear user, Your car booking is done successfully with user "+c.getPostingUserName());
         EmailClient.sendEmail(c.getPostingUserName(), "Car booked successfully!", "Dear user, Your car listing is booked by user "+NeuPlexusHome.useraccount.getUserName());
        panelRight.add("bookingConf",bookingConf);
        CardLayout layout=(CardLayout)panelRight.getLayout();
        layout.next(panelRight);    
}catch(Exception e){
    logger.error("Exception while booking car "+e.getStackTrace());
}
    }//GEN-LAST:event_jbtnBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         panelRight.remove(this);
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBook;
    private javax.swing.JTextField jtxtaccupancy;
    private javax.swing.JTextField jtxtccolor;
    private javax.swing.JTextField jtxtcmodel;
    private javax.swing.JTextField jtxtcname;
    private javax.swing.JTextField jtxtctype;
    private javax.swing.JTextField jtxtdropoffpt;
    private javax.swing.JTextField jtxtfdate;
    private javax.swing.JTextField jtxtflexdistance;
    private javax.swing.JTextField jtxtftime;
    private javax.swing.JTextField jtxtstartpt;
    private javax.swing.JTextField jtxttdate;
    private javax.swing.JTextField jtxtttime;
    private javax.swing.JTextField postingTxt;
    // End of variables declaration//GEN-END:variables

    private void hideBooking() {
       if(NeuPlexusHome.useraccount.getUserName().equalsIgnoreCase(c.getPostingUserName())){
           jbtnBook.setEnabled(false);
       }
       else
           jbtnBook.setEnabled(true);
    }
}
