/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.carPool;

import business.carpool.BookingDetails;
import java.awt.CardLayout;
import javax.swing.JPanel;
import business.carpool.CarDirectory;
import business.carpool.CarInfo;
import business.dataoperations.DataStore;
import business.qnaPortal.Question;
import business.qnaPortal.QuestionDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import neuplexus.NEUPlexus;
import org.apache.log4j.Logger;
import userInterface.authentication.UserLogin;
import userInterface.homeSceen.NeuPlexusHome;
import utils.EmailClient;

/**
 *
 * @author newzysharma
 */
public class BookCarWorkArea extends javax.swing.JPanel {

  //  CarDirectory carDirectory;
    private JPanel panelRight;
    private DataStore datastore;
    private  ArrayList<CarInfo> carList;
    final static Logger logger = Logger.getLogger(BookCarWorkArea.class.getName());

    /**
     * Creates new form BookCarWorkArea
     */
    public BookCarWorkArea(JPanel panelRight, DataStore datastore) {
        initComponents();
        this.panelRight = panelRight;
       // this.carDirectory = carDirectory;
        this.datastore = datastore;
        this.carList = new ArrayList<CarInfo>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtFromLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtToLocation = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        carListTable = new javax.swing.JTable();
        jbtnViewDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FROM");

        jtxtFromLocation.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtFromLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFromLocationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TO");

        jtxtToLocation.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtToLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtToLocationActionPerformed(evt);
            }
        });

        jbtnSearch.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSearch.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jbtnSearch.setText("SEARCH");
        jbtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        carListTable.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        carListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Listing No.", "Car Name", "From", "To", "Available Seats"
            }
        ));
        carListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carListTable);

        jbtnViewDetails.setBackground(new java.awt.Color(0, 0, 0));
        jbtnViewDetails.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        jbtnViewDetails.setText("VIEW DETAILS");
        jbtnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewDetailsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CAR BOOKING WORK AREA");

        btnBack.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFromLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtToLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(686, 686, 686)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(628, 628, 628)
                        .addComponent(btnBack)
                        .addGap(94, 94, 94)
                        .addComponent(jbtnViewDetails)
                        .addGap(83, 83, 83)
                        .addComponent(btnDelete)))
                .addContainerGap(1596, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFromLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtToLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnViewDetails)
                        .addComponent(btnDelete)))
                .addContainerGap(481, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFromLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFromLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFromLocationActionPerformed

    private void jtxtToLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtToLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtToLocationActionPerformed

    private void jbtnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewDetailsActionPerformed
        // TODO add your handling code here:
        try{
        int selected = carListTable.getSelectedRow();
        if(selected>=0){
            CarInfo c = (CarInfo)carListTable.getValueAt(selected, 0);
            panelRight.add("bookCar",new BookCarViewDetails (panelRight,c,datastore));
            
            
        CardLayout layout = (CardLayout)panelRight.getLayout();
           layout.next(panelRight);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row to display","Error",JOptionPane.ERROR_MESSAGE);
        } 
        }catch(Exception e){
            logger.error("Exception while view cars "+e.getStackTrace());
        }
    }//GEN-LAST:event_jbtnViewDetailsActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:
        
       
           searchCar();
        printCarListTable();
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        panelRight.remove(this);
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     int selected = carListTable.getSelectedRow();
        if(selected>=0){
            CarInfo q= (CarInfo)carListTable.getValueAt(selected, 0);
            CarDirectory qdir = datastore.getCardir();
            if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
    qdir.getCarList().remove(q);
            JOptionPane.showMessageDialog(null, "Car Listing deleted successfully!","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
            EmailClient.sendEmail(q.getPostingUserName(), "Car listing deleted", "You have successfullly deleted car listing from portal.");
            if(q.getBookingUserNames().size()!=0){
                for(BookingDetails b:q.getBookingUserNames())
                EmailClient.sendEmail(b.getUserID(), "Car listing removed", "User "+q.getPostingUserName()+" removed car listing from portal. Your booking is automatically canceled with the user.");
            }
            searchCar();
            printCarListTable();
            logger.info("Car listing deleted by user "+NeuPlexusHome.useraccount.getUserName());
} else {
    // no option
}
            
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void carListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carListTableMouseClicked
        int selected = carListTable.getSelectedRow();
        if(selected>=0){
            CarInfo q= (CarInfo)carListTable.getValueAt(selected, 0);
            if(q.getPostingUserName().equalsIgnoreCase(NeuPlexusHome.useraccount.getUserName())){
                btnDelete.setEnabled(true);
            }else{
                btnDelete.setEnabled(false);
            }
        }
    }//GEN-LAST:event_carListTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JTable carListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnViewDetails;
    private javax.swing.JTextField jtxtFromLocation;
    private javax.swing.JTextField jtxtToLocation;
    // End of variables declaration//GEN-END:variables

    private void printCarListTable() {
        int i = 1;
        btnDelete.setVisible(false);
        CarDirectory cdir = datastore.getCardir();
        DefaultTableModel m = (DefaultTableModel) carListTable.getModel();
        m.setRowCount(0);
        for (CarInfo c : cdir.getCarList()) {
            m.addRow(new Object[]{c,c.getCarName(), c.getStartPoint(), c.getDropOffPoint(), c.getOccupancy()});
        }

    }

    private void searchCar() {
        carList.clear();
         for (CarInfo info : datastore.getCardir().getCarList()) {
                if (jtxtFromLocation.getText().equalsIgnoreCase(info.getStartPoint()) && jtxtToLocation.getText().equalsIgnoreCase(info.getDropOffPoint())) {
                   if(!info.isBooked())
                    carList.add(info);
                }
        }
    }

}
