/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.carPool;

import business.carpool.CarInfo;
import business.dataoperations.DataStore;
import business.management.CarListingRequest;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author newzysharma
 */
public class ConfirmCarListDetails extends javax.swing.JPanel {
    private JPanel panelRight;
private DataStore datastore;
CarInfo info;
CarListingRequest carreq;

    /**
     * Creates new form ConfirmBookApartmentDetails
     */
    public ConfirmCarListDetails(JPanel panelRight,DataStore datastore,CarInfo info) {
        initComponents();
          this.panelRight=panelRight;
          this.datastore =datastore;
          this.info = info;
          carreq = new CarListingRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtupload = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnConfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Upload Your Documents");

        jtxtupload.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jbtnBrowse.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBrowse.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Browse.png"))); // NOI18N
        jbtnBrowse.setText("BROWSE");
        jbtnBrowse.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbtnBrowse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBack.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnConfirm.setBackground(new java.awt.Color(0, 0, 0));
        jbtnConfirm.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick.png"))); // NOI18N
        jbtnConfirm.setText("CONFIRM");
        jbtnConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbtnConfirm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DOCUMENTS REQUIRED FOR VERIFICATION");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Document Type:");

        jComboBox1.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Driving License", "Passport" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtupload, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jbtnBrowse))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jbtnConfirm)))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtupload, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtnBrowse))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnConfirm)
                    .addComponent(jbtnBack))
                .addContainerGap(728, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here
        panelRight.remove(this);
        CardLayout layout = (CardLayout) panelRight.getLayout();
        layout.previous(panelRight);
        
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {                                           
       if(carreq.getDocumentPath()==""){
           JOptionPane.showMessageDialog(null, "Please select a file to upload","ERROR",JOptionPane.ERROR);
       }
        carreq.setDocumentType(jComboBox1.getSelectedItem().toString());
        carreq.setCarinfo(info);
        carreq.setStatus("Pending");
        carreq.setRequestNumber();
        datastore.getCarmngmntrqstqueue().getRequests().add(carreq);
         JOptionPane.showMessageDialog(null, "Request sent for admin approval!","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
    }                                        

    private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(null);
        File file = filechooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        jtxtupload.setText(filename);
        carreq.setDocumentPath(filename);
    }//GEN-LAST:event_jbtnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnConfirm;
    private javax.swing.JTextField jtxtupload;
    // End of variables declaration//GEN-END:variables
}