/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.homeSceen;
import business.dataoperations.DataStore;
import business.enterprise.Enterprise;
import business.organization.UserOrganization;
import business.userAccount.User;
import java.awt.CardLayout;
import neuplexus.NEUPlexus;
import userInterface.QnAPortal.AboutQnA;
import userInterface.accomodation.AboutAccomodation;
import userInterface.authentication.UserLogin;
import userInterface.carPool.AboutCarPool;
import utils.DB4Outil;

/**
 *
 * @author Shardul Pathak
 */
public class NeuPlexusHome extends javax.swing.JFrame {
            public static NeuPlexusHome homeObject;


    /**
     * Creates new form NeuPlexusHome
     */
    public static User useraccount=null;
    public static Enterprise inEnterprise=null;
    public static UserOrganization inOrganization=null;
    public static NEUPlexus system=null;
    public DataStore datastore;
    private DB4Outil dB4OUtil = DB4Outil.getInstance();

    public NeuPlexusHome() {
        initComponents();
        btnViewProfile.setVisible(false);
                        this.homeObject=homeObject;

     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelLeft = new javax.swing.JPanel();
        btnAboutQnAPortal = new javax.swing.JButton();
        btnAboutAccomodationPortal = new javax.swing.JButton();
        btnAboutCarPooling = new javax.swing.JButton();
        btnUserLogin = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        panelRight = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panelLeft.setBackground(new java.awt.Color(153, 0, 0));

        btnAboutQnAPortal.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnAboutQnAPortal.setText("QnA Portal");
        btnAboutQnAPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutQnAPortalActionPerformed(evt);
            }
        });

        btnAboutAccomodationPortal.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnAboutAccomodationPortal.setText("Accommodation Portal");
        btnAboutAccomodationPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutAccomodationPortalActionPerformed(evt);
            }
        });

        btnAboutCarPooling.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnAboutCarPooling.setText("Car Pooling");
        btnAboutCarPooling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutCarPoolingActionPerformed(evt);
            }
        });

        btnUserLogin.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnUserLogin.setText("User Login");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        btnViewProfile.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUserLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAboutQnAPortal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAboutAccomodationPortal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAboutCarPooling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnAboutQnAPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnAboutAccomodationPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnAboutCarPooling, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelLeft);

        panelRight.setBackground(new java.awt.Color(0, 0, 0));
        panelRight.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to NEU PLEXUS");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setIconTextGap(10);
        panelRight.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(panelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutQnAPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutQnAPortalActionPerformed
        // TODO add your handling code here:
        if(useraccount==null){
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("aboutQnA", new AboutQnA(panelRight));
        layout.next(panelRight);
        }
        else{
          CardLayout layout=(CardLayout)panelRight.getLayout();
           panelRight.add("qnaMainWorkArea",useraccount.getRole().createWorkArea(panelRight, useraccount, inOrganization, inEnterprise, system,1));
           layout.next(panelRight);
       }
  
    }//GEN-LAST:event_btnAboutQnAPortalActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
        if(btnUserLogin.getText().equalsIgnoreCase("User Login")){
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("login" , new UserLogin(panelRight,this,true));
        layout.next(panelRight);
        }else{
          afterLogout();
        }
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
       CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("viewProfile" , new ViewProfilePanel(panelRight,homeObject));
        layout.next(panelRight);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnAboutAccomodationPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutAccomodationPortalActionPerformed
       if(useraccount==null || useraccount.getRole().toString().equalsIgnoreCase("AlumniRole")){
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("aboutAcco",new AboutAccomodation(panelRight));
        layout.next(panelRight);
        }
        else
        {
            CardLayout layout = (CardLayout)panelRight.getLayout();
            panelRight.add("accomodationWorkArea",useraccount.getRole().createWorkArea(panelRight, useraccount, inOrganization, inEnterprise, system,3));
            layout.next(panelRight);
        }
        
    }//GEN-LAST:event_btnAboutAccomodationPortalActionPerformed

    private void btnAboutCarPoolingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutCarPoolingActionPerformed

        // TODO add your handling code here:
        if(useraccount==null || useraccount.getRole().toString().equalsIgnoreCase("IncomingStudentRole")){
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("aboutCarPool",new AboutCarPool(panelRight));
        layout.next(panelRight);
        }
        else
        {
            CardLayout layout = (CardLayout)panelRight.getLayout();
            panelRight.add("carPoolWorkArea",useraccount.getRole().createWorkArea(panelRight, useraccount, inOrganization, inEnterprise, system,2));
            layout.next(panelRight);
        }
        
    }//GEN-LAST:event_btnAboutCarPoolingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NeuPlexusHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NeuPlexusHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NeuPlexusHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NeuPlexusHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NeuPlexusHome().setVisible(true);
            }
        });
    }
    
    public void afterLogin(){
        //if(.equalsIgnoreCase(anotherString))
             switch(useraccount.getRole().toString()){
        case "CurrentStudentRole": btnViewProfile.setVisible(true);;
                                     break;
        case "IncomingStudentRole": btnViewProfile.setVisible(true);
                                     break;
        case "Alumni":  btnViewProfile.setVisible(true);
                       
                                     break;   
        case "Admin": btnViewProfile.setVisible(false);
                                     break;   
        case "Manager": btnViewProfile.setVisible(false);
                                     break;   
        case "SystemAdminRole": btnViewProfile.setVisible(false);
                                     // user.setPhoto("/images/sysadmin.png");
                                     break;   
             }
        
        btnUserLogin.setText("Logout");
    }
    
    public void disableEntButtons(){
        btnAboutQnAPortal.setVisible(false);
        btnAboutCarPooling.setVisible(false);
        btnAboutAccomodationPortal.setVisible(false);
    }
    
    public void enableEntButtons(){
        btnAboutQnAPortal.setVisible(true);
        btnAboutCarPooling.setVisible(true);
        btnAboutAccomodationPortal.setVisible(true);
    }
   
    public void afterLogout(){
        useraccount=null;    
        btnUserLogin.setText("User Login");
        btnViewProfile.setVisible(false);
        enableEntButtons();
        //system.getUserAccountDirectory().logout();
        //UserLogin.storeSystem();
        dB4OUtil.storeSystem(UserLogin.system);
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("login" , new UserLogin(panelRight,this,false));
        layout.next(panelRight);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutAccomodationPortal;
    private javax.swing.JButton btnAboutCarPooling;
    private javax.swing.JButton btnAboutQnAPortal;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    // End of variables declaration//GEN-END:variables
}
