/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.homeSceen;

import business.dataoperations.DataStore;
import business.userAccount.User;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Apurva
 */
public class ViewProfilePanel extends javax.swing.JPanel {

    JPanel panelRight;
        public static NeuPlexusHome homeObject;
        final static Logger logger = Logger.getLogger(ViewProfilePanel.class.getName());

    /**
     * Creates new form ViewProfilePanel
     */
    public ViewProfilePanel(JPanel panelRight,NeuPlexusHome homeObject) {
        initComponents();
        this.panelRight=panelRight;

                this.homeObject=homeObject;

        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        contactTxt = new javax.swing.JTextField();
        campusTxt = new javax.swing.JTextField();
        roleTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        majortxt = new javax.swing.JTextField();
        dogTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        nuidTxt1 = new javax.swing.JTextField();
        pictureLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Number");

        jLabel4.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Campus");

        jLabel5.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Role");

        nameLabel.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Firstname Middle Lastname");

        usernameTxt.setEditable(false);
        usernameTxt.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        usernameTxt.setEnabled(false);
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });

        contactTxt.setEditable(false);
        contactTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        contactTxt.setEnabled(false);
        contactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTxtActionPerformed(evt);
            }
        });

        campusTxt.setEditable(false);
        campusTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        campusTxt.setEnabled(false);
        campusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campusTxtActionPerformed(evt);
            }
        });

        roleTxt.setEditable(false);
        roleTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        roleTxt.setEnabled(false);
        roleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Graduation");

        jLabel7.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");

        dobTxt.setEditable(false);
        dobTxt.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        dobTxt.setEnabled(false);
        dobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtActionPerformed(evt);
            }
        });

        majortxt.setEditable(false);
        majortxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        majortxt.setEnabled(false);
        majortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majortxtActionPerformed(evt);
            }
        });

        dogTxt.setEditable(false);
        dogTxt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        dogTxt.setEnabled(false);
        dogTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogTxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DOB");

        jLabel9.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Major");

        addressTxt.setEditable(false);
        addressTxt.setColumns(20);
        addressTxt.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        addressTxt.setRows(5);
        addressTxt.setEnabled(false);
        jScrollPane1.setViewportView(addressTxt);

        jLabel10.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NUID");

        nuidTxt1.setEditable(false);
        nuidTxt1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        nuidTxt1.setEnabled(false);
        nuidTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuidTxt1ActionPerformed(evt);
            }
        });

        pictureLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(619, 619, 619)
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nuidTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(majortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dogTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(658, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(majortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(nuidTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(dogTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void contactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTxtActionPerformed

    private void campusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campusTxtActionPerformed

    private void roleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleTxtActionPerformed

    private void dobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTxtActionPerformed

    private void majortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majortxtActionPerformed

    private void dogTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dogTxtActionPerformed

    private void nuidTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuidTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuidTxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JTextField campusTxt;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField dogTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField majortxt;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nuidTxt1;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JTextField roleTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
        //Photo display is remaining
        try{
      User user = NeuPlexusHome.useraccount;
      if(user.getFirstName()!=null && user.getMiddleName()!=null && user.getLastName()!=null)
      nameLabel.setText(user.getFirstName()+" "+user.getMiddleName()+" "+user.getLastName());
     
      usernameTxt.setText(user.getUserName());
      if(user.getCampusName()!=null)
      campusTxt.setText(user.getCampusName());
      if(user.getContactNumber()!=null)
      contactTxt.setText(user.getContactNumber());
      String roleValue="";
      switch(user.getRole().toString()){
        case "CurrentStudentRole": roleValue = "Current Student";
                                     break;
        case "IncomingStudentRole": roleValue = "Incoming Student";
                                     break;
        case "Alumni": roleValue = "Alumni";
                       
                                     break;   
        case "Admin": roleValue = "Admin";
                        user.setPhoto("/images/entadmin.png");
                                     break;   
        case "Manager": roleValue = "Manager";
                          user.setPhoto("/images/manager.png");
                                     break;   
        case "SystemAdminRole": roleValue = "System Admin Role";
                                      user.setPhoto("/images/sysadmin.png");
                                     break;   
      }
      roleTxt.setText(roleValue);
      Date d =null;
      DateFormat df=null;
      if(user.getDateOfBirth()!=null){
      d=user.getDateOfBirth();
      df = new SimpleDateFormat("MM/dd/yyyy");
      dobTxt.setText(df.format(d));
      }
      if(user.getDateOFGraduation()!=null){
      d =user.getDateOFGraduation();
      dogTxt.setText(df.format(d));
      }
      if(user.getMajor()!=null)
      majortxt.setText(user.getMajor());
      String address="";
      if(user.getUserAddress().getLine1()!=null){
      address = user.getUserAddress().getLine1()+"\n"+user.getUserAddress().getLine2()+"\n"+user.getUserAddress().getCity()+"\n"+user.getUserAddress().getState()+"\n"+user.getUserAddress().getZipCode();
      addressTxt.setText(address);
      }
      
      if(user.getNUID()!=0)
          nuidTxt1.setText(String.valueOf(user.getNUID()));
    //  showProfilePic(user.getPhoto());
        }catch(Exception e){
            logger.error("Exception while displaying profile "+e.getStackTrace());
        }
    }
    
    public void showProfilePic(String path){
       BufferedImage loadedImage = null;
          try {
              File file = new File(path);
              String filepath = file.getAbsolutePath();
              File f = file.getAbsoluteFile();
           // loadedImage = ImageIO.read(f);
              loadedImage = ImageIO.read(new FileInputStream(path));
            
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
     
        ImageIcon image = new ImageIcon(loadedImage);

        pictureLabel.setIcon(image);
        pictureLabel.setVisible(true);
    }
}
