/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.accomodation;

import business.dataoperations.DataStore;
import business.enterprise.Enterprise;
import business.role.Role;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.carPool.ListCarWorkArea;

/**
 *
 * @author newzysharma
 */
public class AccomodationMainWorkArea extends javax.swing.JPanel {
    private JPanel panelRight;
    private DataStore datastore;

    /**
     * Creates new form AccomodationMainWorkArea
     */
    public AccomodationMainWorkArea(JPanel panelRight,Enterprise enterprise,DataStore datastore) {
        initComponents();
        this.panelRight=panelRight;
        this.datastore =datastore;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnListApt = new javax.swing.JButton();
        jbtnSearchApartment = new javax.swing.JButton();
        jbtnViewBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jbtnListApt.setBackground(new java.awt.Color(153, 0, 0));
        jbtnListApt.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnListApt.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListApt.setText("List Your Apartment Here");
        jbtnListApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListAptActionPerformed(evt);
            }
        });

        jbtnSearchApartment.setBackground(new java.awt.Color(153, 0, 0));
        jbtnSearchApartment.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnSearchApartment.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSearchApartment.setText("Search For Apartment");
        jbtnSearchApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchApartmentActionPerformed(evt);
            }
        });

        jbtnViewBooking.setBackground(new java.awt.Color(153, 0, 0));
        jbtnViewBooking.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnViewBooking.setForeground(new java.awt.Color(255, 255, 255));
        jbtnViewBooking.setText("View Bookings Here");
        jbtnViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewBookingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACCOMMODATION PORTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnViewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSearchApartment, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnListApt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(jLabel1)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(jbtnListApt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbtnSearchApartment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jbtnViewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnListAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListAptActionPerformed
        // TODO add your handling code here:
        CardLayout layout= (CardLayout)panelRight.getLayout();
        panelRight.add("listYourAppartment", new ListApartmentWorkArea(panelRight,datastore));
        layout.next(panelRight);
    }//GEN-LAST:event_jbtnListAptActionPerformed

    private void jbtnSearchApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchApartmentActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("searchAptWorkArea",new SearchApartmentWorkArea(panelRight,datastore));
        layout.next(panelRight);
    }//GEN-LAST:event_jbtnSearchApartmentActionPerformed

    private void jbtnViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewBookingActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("viewBookingsWorkArea",new ViewBookingsWorkArea(panelRight,datastore));
        layout.next(panelRight);
    }//GEN-LAST:event_jbtnViewBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnListApt;
    private javax.swing.JButton jbtnSearchApartment;
    private javax.swing.JButton jbtnViewBooking;
    // End of variables declaration//GEN-END:variables
}
