/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.accomodation;

import business.accomodation.Accomodation;
import business.accomodation.Address;
import business.dataoperations.DataStore;
import business.management.AccomodationListRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import userInterface.carPool.ConfirmCarListDetails;
import userInterface.homeSceen.NeuPlexusHome;

/**
 *
 * @author newzysharma
 */
public class ListApartmentWorkArea extends javax.swing.JPanel {
private JPanel panelRight;
private DataStore datastore;
final static Logger logger = Logger.getLogger(ListApartmentWorkArea.class.getName());
    /**
     * Creates new form ListApartmentWorkArea
     */
    public ListApartmentWorkArea(JPanel panelRight,DataStore datastore) {
        initComponents();
        this.panelRight=panelRight;
        this.datastore =datastore;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtaptype = new javax.swing.JTextField();
        jtxtaline1 = new javax.swing.JTextField();
        jtxtaline2 = new javax.swing.JTextField();
        jtxtzipcode = new javax.swing.JTextField();
        jtxtstate = new javax.swing.JTextField();
        jtxtcity = new javax.swing.JTextField();
        jtxtpentpermonth = new javax.swing.JTextField();
        jbtnBack = new javax.swing.JButton();
        jbtnSubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtdisfuniv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtFacilities = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jtxtavfdate = new org.jdesktop.swingx.JXDatePicker();
        jtxtavldate = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apartment Type");

        jLabel2.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address Line 1");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address Line 2");

        jLabel4.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ZIP Code");

        jLabel5.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("State");

        jLabel6.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("City");

        jLabel7.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rent per Month");

        jLabel8.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ENTER YOUR APARTMENT DETAILS");

        jtxtaptype.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtaptype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaptypeActionPerformed(evt);
            }
        });

        jtxtaline1.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtaline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaline1ActionPerformed(evt);
            }
        });

        jtxtaline2.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jtxtzipcode.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jtxtstate.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jtxtcity.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jtxtpentpermonth.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jbtnBack.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBack.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSubmit.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jbtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick.png"))); // NOI18N
        jbtnSubmit.setText("SUBMIT");
        jbtnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Available From Date");

        jLabel10.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Available Till Date");

        jLabel11.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Facilities");

        jLabel12.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Distance From University");

        jtxtdisfuniv.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N

        jtxtFacilities.setColumns(20);
        jtxtFacilities.setFont(new java.awt.Font("Charter", 0, 16)); // NOI18N
        jtxtFacilities.setRows(5);
        jScrollPane1.setViewportView(jtxtFacilities);

        jLabel13.setFont(new java.awt.Font("Charter", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mile(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtaline2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtstate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtpentpermonth, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtaline1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtaptype, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtdisfuniv, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtavfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtavldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(648, 648, 648)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(713, 713, 713)
                        .addComponent(jbtnBack)
                        .addGap(33, 33, 33)
                        .addComponent(jbtnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel8)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtaptype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtaline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtaline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtpentpermonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jtxtavfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtavldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtdisfuniv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSubmit)
                            .addComponent(jbtnBack)))
                    .addComponent(jLabel11))
                .addContainerGap(846, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtaptypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaptypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaptypeActionPerformed

    private void jtxtaline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaline1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaline1ActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
try{
        Accomodation accomodation = getData();

       
        CardLayout layout= (CardLayout)panelRight.getLayout();
        panelRight.add("confirmBookAptDetails", new ConfirmBookApartmentDetails(panelRight,datastore,accomodation));
        layout.next(panelRight);
}catch(Exception e){
    logger.error("Exception while listing accommodation "+e.getStackTrace());
}
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    private void jtxtavfdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtavfdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtavfdateActionPerformed
    
    private Accomodation getData(){
        Accomodation accomodation = new Accomodation();
        Address address = new Address();
        try{
            if(!jtxtaptype.getText().equals("") && !jtxtaline1.getText().equals("") && !jtxtaline2.getText().equals("") &&
                    jtxtavfdate!=null && jtxtavldate!=null && !jtxtcity.getText().equals("")
                    && !jtxtpentpermonth.getText().equals("") && !jtxtstate.getText().equals("") && !jtxtzipcode.getText().equals("") &&
                    !jtxtdisfuniv.getText().equals("") && !jtxtFacilities.getText().equals("")){
                
                accomodation.setTypeOfAccomodation(jtxtaptype.getText());
                
                address.setLine1(jtxtaline1.getText());
                address.setLine2(jtxtaline2.getText());
                address.setCity(jtxtcity.getText());
                address.setState(jtxtstate.getText());
                address.setZipCode(jtxtzipcode.getText());
                accomodation.setAddressOfApartment(address);
                
                DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                accomodation.setAvlFromDate(jtxtavfdate.getDate());
                accomodation.setAvlToDate(jtxtavldate.getDate());
                
                accomodation.setRent(Float.parseFloat(jtxtpentpermonth.getText()));
                accomodation.setDistanceFromUni(Float.parseFloat(jtxtdisfuniv.getText()));
                accomodation.setFacilities(jtxtFacilities.getText());
                accomodation.setOwnerUserName(NeuPlexusHome.useraccount.getUserName());
                accomodation.setAccListNo(0);
                
              //  JOptionPane.showMessageDialog(null, "Accommodation Detail Saved Successfully!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                
                jtxtaline1.setText("");
                jtxtaline2.setText("");
                jtxtaptype.setText("");
             //   jtxtavfdate.setText("");
               // jtxtavtdate.setText("");
                jtxtcity.setText("");
                jtxtpentpermonth.setText("");
                jtxtstate.setText("");
                jtxtzipcode.setText("");
                jtxtdisfuniv.setText("");
                jtxtFacilities.setText("");
            
                
            }else{
                JOptionPane.showMessageDialog(null, "One or more fields is empty");
                return null;
            }
            
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter valid values");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        
        return accomodation;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JTextArea jtxtFacilities;
    private javax.swing.JTextField jtxtaline1;
    private javax.swing.JTextField jtxtaline2;
    private javax.swing.JTextField jtxtaptype;
    private org.jdesktop.swingx.JXDatePicker jtxtavfdate;
    private org.jdesktop.swingx.JXDatePicker jtxtavldate;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtdisfuniv;
    private javax.swing.JTextField jtxtpentpermonth;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxtzipcode;
    // End of variables declaration//GEN-END:variables
}
